// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCITQW69Q3NK5uVGDbiEWXnCDWsrhs6Chw',
    appId: '1:1073854986367:web:ca7c55a17297bd853fa74a',
    messagingSenderId: '1073854986367',
    projectId: 'darmbankbd',
    authDomain: 'darmbankbd.firebaseapp.com',
    storageBucket: 'darmbankbd.appspot.com',
    measurementId: 'G-GW5FDP0GNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBHpbeeGXasgLsiZ9dWu_IoqhqSZV4OjY',
    appId: '1:1073854986367:android:ae8065552621e2173fa74a',
    messagingSenderId: '1073854986367',
    projectId: 'darmbankbd',
    storageBucket: 'darmbankbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsioIZyfhJ-vAcDD2UfIBaBpMBx2LgTVw',
    appId: '1:1073854986367:ios:b5f080710c89b2893fa74a',
    messagingSenderId: '1073854986367',
    projectId: 'darmbankbd',
    storageBucket: 'darmbankbd.appspot.com',
    iosClientId: '1073854986367-fu5bvc9uinpm8dmoqbi5a7tlpjt53up9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankDarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsioIZyfhJ-vAcDD2UfIBaBpMBx2LgTVw',
    appId: '1:1073854986367:ios:b5f080710c89b2893fa74a',
    messagingSenderId: '1073854986367',
    projectId: 'darmbankbd',
    storageBucket: 'darmbankbd.appspot.com',
    iosClientId: '1073854986367-fu5bvc9uinpm8dmoqbi5a7tlpjt53up9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankDarm',
  );
}
