name: bank_darm
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^5.1.0
  brasil_fields: ^1.9.1
  firebase_core: ^2.4.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  go_router: ^7.1.1
  image_picker: ^0.8.0+3
  fluttertoast: any



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/card.png
    - assets/money.png
    - assets/sprinkle.png

